use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

use crate::lockfile::LockedPackage;
use crate::registry::DownloadResult;

/// Generate a proper CMake config file for a package.
///
/// Strategy:
/// 1. If the extracted package has its own `*Config.cmake` → wrap it (forward to it).
/// 2. Otherwise, generate a fresh `{Name}Config.cmake` from the known include/lib paths.
pub fn generate_config_file(
    pkg: &LockedPackage,
    download: &DownloadResult,
    cmake_dir: &Path,
) -> Result<PathBuf> {
    std::fs::create_dir_all(cmake_dir)
        .context("Failed to create Ion CMake directory")?;

    // Check if the package ships its own CMake config files
    let shipped_config = find_shipped_cmake_config(&download.extracted_path, &pkg.name);

    let config_content = if let Some(shipped) = shipped_config {
        // Generate a forwarding file that adds the package's cmake dir to the prefix path
        generate_forwarding_config(pkg, &shipped)
    } else {
        // Generate a full config file from scratch
        generate_full_config(pkg, download)
    };

    // Write {Name}Config.cmake
    let canonical_name = cmake_canonical_name(&pkg.name);
    let config_path = cmake_dir.join(format!("{}Config.cmake", canonical_name));
    std::fs::write(&config_path, config_content)
        .with_context(|| format!("Failed to write CMake config for {}", pkg.name))?;

    // Also write {name}-config.cmake (lowercase form, both are searched by find_package)
    let lower_config_path = cmake_dir.join(format!("{}-config.cmake", pkg.name.to_lowercase()));
    if lower_config_path != config_path {
        // Symlink or copy
        let _ = std::fs::remove_file(&lower_config_path);
        #[cfg(unix)]
        std::os::unix::fs::symlink(config_path.file_name().unwrap(), &lower_config_path)?;
        #[cfg(not(unix))]
        std::fs::copy(&config_path, &lower_config_path)?;
    }

    // Write {Name}ConfigVersion.cmake for version checking
    let version_content = generate_version_config(pkg);
    let version_path = cmake_dir.join(format!("{}ConfigVersion.cmake", canonical_name));
    std::fs::write(&version_path, version_content)
        .with_context(|| format!("Failed to write CMake version config for {}", pkg.name))?;

    Ok(config_path)
}

/// Look for shipped CMake config files in the extracted package
fn find_shipped_cmake_config(extracted_path: &Path, name: &str) -> Option<PathBuf> {
    let canonical = cmake_canonical_name(name);
    let lower = name.to_lowercase();

    let candidates = [
        // Standard locations
        format!("{}Config.cmake", canonical),
        format!("{}-config.cmake", lower),
        // Nested in cmake/ subdirectory
        format!("cmake/{}Config.cmake", canonical),
        format!("cmake/{}-config.cmake", lower),
        // Nested in lib/cmake/
        format!("lib/cmake/{}/{}Config.cmake", name, canonical),
        format!("lib/cmake/{}/{}-config.cmake", name, lower),
        // Some packages use share/cmake/
        format!("share/cmake/{}/{}Config.cmake", name, canonical),
    ];

    for candidate in &candidates {
        let p = extracted_path.join(candidate);
        if p.exists() {
            return Some(p);
        }
    }

    // Deep search
    let pattern = format!("{}Config.cmake", canonical);
    walkdir::WalkDir::new(extracted_path)
        .max_depth(6)
        .into_iter()
        .filter_map(|e| e.ok())
        .find(|e| {
            e.file_name()
                .to_str()
                .map(|n| n == pattern || n == format!("{}-config.cmake", lower))
                .unwrap_or(false)
        })
        .map(|e| e.into_path())
}

/// Generate a forwarding config that points to the package's own CMake config
fn generate_forwarding_config(pkg: &LockedPackage, shipped_config: &Path) -> String {
    let config_dir = shipped_config
        .parent()
        .map(|p| p.display().to_string())
        .unwrap_or_default();

    format!(
        r#"# Ion-generated forwarding config for {name} {version}
# This file forwards to the cmake config shipped with the package.
# Do not edit manually — regenerated by `ion install`.

cmake_minimum_required(VERSION 3.15)

set({canonical}_FOUND TRUE)
set({canonical}_VERSION "{version}")

# Add the package's own cmake directory to the prefix path
list(APPEND CMAKE_PREFIX_PATH "{config_dir}")
list(APPEND CMAKE_MODULE_PATH "{config_dir}")

# Forward to the shipped config
include("{shipped_config}")
"#,
        name = pkg.name,
        canonical = cmake_canonical_name(&pkg.name),
        version = pkg.version,
        config_dir = config_dir,
        shipped_config = shipped_config.display(),
    )
}

/// Generate a full CMake config file with modern target-based interface
fn generate_full_config(pkg: &LockedPackage, download: &DownloadResult) -> String {
    let canonical = cmake_canonical_name(&pkg.name);
    let extracted = download.extracted_path.display();

    // Build include directories list
    let include_dirs = if download.include_dirs.is_empty() {
        format!("\"{}\"", extracted)
    } else {
        download
            .include_dirs
            .iter()
            .map(|p| format!("\"{}\"", p.display()))
            .collect::<Vec<_>>()
            .join("\n        ")
    };

    // Determine if this is header-only (no lib files)
    let is_header_only = download.lib_files.is_empty();

    let target_definitions = if is_header_only {
        generate_header_only_target(pkg, &include_dirs)
    } else {
        generate_library_targets(pkg, download, &include_dirs)
    };

    format!(
        r#"# Auto-generated by Ion {ion_version} — do not edit manually.
# Regenerated on every `ion install`. Commit this file is NOT needed.
#
# Package: {name} {version}
# Source:  {source}

cmake_minimum_required(VERSION 3.15)

# Guard against double-inclusion
if({canonical}_FOUND)
    return()
endif()

set({canonical}_FOUND TRUE)
set({canonical}_VERSION "{version}")
set({canonical}_VERSION_MAJOR {major})
set({canonical}_VERSION_MINOR {minor})
set({canonical}_VERSION_PATCH {patch})

# Package root directory
set({canonical}_ROOT_DIR "{extracted}")

# Legacy variables (for projects using old-style find_package)
set({canonical}_INCLUDE_DIRS {include_dirs})

{target_definitions}

# Mark as found for CMake's find_package system
set({canonical}_FOUND TRUE PARENT_SCOPE CACHE BOOL "" FORCE)
"#,
        ion_version = env!("CARGO_PKG_VERSION"),
        name = pkg.name,
        canonical = canonical,
        version = pkg.version,
        source = pkg.source,
        extracted = extracted,
        include_dirs = include_dirs,
        major = version_part(&pkg.version, 0),
        minor = version_part(&pkg.version, 1),
        patch = version_part(&pkg.version, 2),
        target_definitions = target_definitions,
    )
}

fn generate_header_only_target(pkg: &LockedPackage, include_dirs: &str) -> String {
    let canonical = cmake_canonical_name(&pkg.name);
    let target = if pkg.cmake_targets.is_empty() {
        format!("{}::{}", pkg.name, pkg.name)
    } else {
        pkg.cmake_targets[0].clone()
    };

    format!(
        r#"# Header-only interface target
if(NOT TARGET {target})
    add_library({target} INTERFACE IMPORTED GLOBAL)
    set_target_properties({target} PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "{include_dirs}"
    )
    target_compile_features({target} INTERFACE cxx_std_11)
endif()
"#,
        target = target,
        include_dirs = include_dirs,
    )
}

fn generate_library_targets(
    pkg: &LockedPackage,
    download: &DownloadResult,
    include_dirs: &str,
) -> String {
    let mut parts = Vec::new();
    let canonical = cmake_canonical_name(&pkg.name);

    for (i, lib_path) in download.lib_files.iter().enumerate() {
        let target = if i < pkg.cmake_targets.len() {
            pkg.cmake_targets[i].clone()
        } else {
            format!("{}::{}", pkg.name, pkg.name)
        };

        let lib_type = if lib_path
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| matches!(e, "a" | "lib"))
            .unwrap_or(false)
        {
            "STATIC"
        } else {
            "SHARED"
        };

        parts.push(format!(
            r#"if(NOT TARGET {target})
    add_library({target} {lib_type} IMPORTED GLOBAL)
    set_target_properties({target} PROPERTIES
        IMPORTED_LOCATION "{lib_path}"
        INTERFACE_INCLUDE_DIRECTORIES "{include_dirs}"
    )
    target_compile_features({target} INTERFACE cxx_std_11)
endif()
"#,
            target = target,
            lib_type = lib_type,
            lib_path = lib_path.display(),
            include_dirs = include_dirs,
        ));
    }

    parts.join("\n")
}

/// Generate {Name}ConfigVersion.cmake for CMake version compatibility checks
fn generate_version_config(pkg: &LockedPackage) -> String {
    format!(
        r#"# Version config for {name} — generated by Ion.
# Supports: find_package({name} VERSION x.y.z)

set(PACKAGE_VERSION "{version}")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
"#,
        name = pkg.name,
        version = pkg.version,
    )
}

/// Convert a package name to the CMake canonical form (PascalCase)
/// e.g. "nlohmann_json" → "nlohmann_json", "fmt" → "fmt", "my-lib" → "MyLib"
pub fn cmake_canonical_name(name: &str) -> String {
    // Well-known packages with specific CMake naming conventions
    match name.to_lowercase().as_str() {
        "fmt" => "fmt".to_string(),
        "spdlog" => "spdlog".to_string(),
        "catch2" => "Catch2".to_string(),
        "eigen" | "eigen3" => "Eigen3".to_string(),
        "boost" => "Boost".to_string(),
        "nlohmann_json" | "nlohmann-json" | "json" => "nlohmann_json".to_string(),
        "gtest" | "googletest" => "GTest".to_string(),
        "zlib" => "ZLIB".to_string(),
        "openssl" => "OpenSSL".to_string(),
        "curl" => "CURL".to_string(),
        "sqlite3" => "SQLite3".to_string(),
        "protobuf" => "Protobuf".to_string(),
        "grpc" => "gRPC".to_string(),
        _ => {
            // Convert hyphenated names to PascalCase
            if name.contains('-') {
                name.split('-')
                    .map(|part| {
                        let mut c = part.chars();
                        match c.next() {
                            None => String::new(),
                            Some(f) => f.to_uppercase().to_string() + c.as_str(),
                        }
                    })
                    .collect()
            } else {
                name.to_string()
            }
        }
    }
}

fn version_part(version: &str, index: usize) -> u64 {
    version
        .split('.')
        .nth(index)
        .and_then(|p| p.parse().ok())
        .unwrap_or(0)
}
