use anyhow::{Context, Result};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;

pub const LOCKFILE_NAME: &str = "ion.lock";
pub const LOCKFILE_VERSION: u32 = 1;

/// A fully resolved, pinned snapshot of all dependencies.
/// Commit this file to version control for reproducible builds.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Lockfile {
    /// Lockfile format version
    pub version: u32,
    /// Timestamp of when the lockfile was generated
    pub generated_at: String,
    /// Content hash of the ion.toml that produced this lock
    pub manifest_hash: String,
    /// All resolved packages (direct + transitive)
    #[serde(default)]
    pub packages: Vec<LockedPackage>,
}

/// A pinned package entry in the lockfile.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct LockedPackage {
    /// Package name (canonical identifier)
    pub name: String,
    /// Exact pinned version
    pub version: String,
    /// Registry source URL/identifier
    pub source: String,
    /// SHA-256 checksum of the downloaded archive, hex encoded
    pub checksum: String,
    /// CMake import targets this package provides
    #[serde(default)]
    pub cmake_targets: Vec<String>,
    /// Names of direct dependencies (name + version pairs)
    #[serde(default)]
    pub dependencies: Vec<String>,
    /// Whether this is a dev-only dependency
    #[serde(default)]
    pub dev_only: bool,
    /// Optional: features enabled for this package
    #[serde(default)]
    pub features: Vec<String>,
}

impl Lockfile {
    /// Create a new empty lockfile
    pub fn new(manifest_hash: impl Into<String>) -> Self {
        Self {
            version: LOCKFILE_VERSION,
            generated_at: Utc::now().to_rfc3339(),
            manifest_hash: manifest_hash.into(),
            packages: Vec::new(),
        }
    }

    /// Load lockfile from disk. Returns None if file doesn't exist.
    pub fn load(project_root: &Path) -> Result<Option<Self>> {
        let path = project_root.join(LOCKFILE_NAME);
        if !path.exists() {
            return Ok(None);
        }
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {}", LOCKFILE_NAME))?;
        let lockfile: Lockfile = toml::from_str(&content)
            .with_context(|| format!("Failed to parse {}", LOCKFILE_NAME))?;
        Ok(Some(lockfile))
    }

    /// Save lockfile to disk
    pub fn save(&self, project_root: &Path) -> Result<()> {
        let path = project_root.join(LOCKFILE_NAME);
        let header = "# This file is automatically generated by Ion. Do not edit manually.\n\
                       # Commit this file to version control for reproducible builds.\n\n";
        let content = toml::to_string_pretty(self).context("Failed to serialize lockfile")?;
        std::fs::write(&path, format!("{}{}", header, content))
            .with_context(|| format!("Failed to write {}", LOCKFILE_NAME))?;
        Ok(())
    }

    /// Add or update a package entry
    pub fn upsert(&mut self, pkg: LockedPackage) {
        if let Some(existing) = self.packages.iter_mut().find(|p| p.name == pkg.name) {
            *existing = pkg;
        } else {
            self.packages.push(pkg);
        }
    }

    /// Remove a package by name
    pub fn remove(&mut self, name: &str) {
        self.packages.retain(|p| p.name != name);
        // Also clean up references in other packages' dependency lists
        for pkg in &mut self.packages {
            pkg.dependencies
                .retain(|d| !d.starts_with(&format!("{} ", name)) && d != name);
        }
    }

    /// Get a package by name
    pub fn get(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }

    /// Build a map of name → LockedPackage for quick lookups
    pub fn as_map(&self) -> HashMap<&str, &LockedPackage> {
        self.packages.iter().map(|p| (p.name.as_str(), p)).collect()
    }

    /// Check if the manifest hash matches (lockfile is still valid)
    pub fn is_fresh(&self, current_manifest_hash: &str) -> bool {
        self.manifest_hash == current_manifest_hash
    }

    /// Return all non-dev packages in dependency order
    pub fn runtime_packages(&self) -> impl Iterator<Item = &LockedPackage> {
        self.packages.iter().filter(|p| !p.dev_only)
    }
}

/// Compute a stable hash of the ion.toml content for freshness checks
pub fn hash_manifest(content: &str) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    hex::encode(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_lockfile_create_save_load() {
        let dir = TempDir::new().unwrap();
        let mut lock = Lockfile::new("abc123");
        lock.upsert(LockedPackage {
            name: "fmt".to_string(),
            version: "10.2.1".to_string(),
            source: "ion+https://registry.ion-cpp.dev".to_string(),
            checksum: "sha256:deadbeef".to_string(),
            cmake_targets: vec!["fmt::fmt".to_string()],
            dependencies: vec![],
            dev_only: false,
            features: vec![],
        });

        lock.save(dir.path()).unwrap();
        let loaded = Lockfile::load(dir.path()).unwrap().unwrap();
        assert_eq!(loaded.packages.len(), 1);
        assert_eq!(loaded.packages[0].name, "fmt");
        assert_eq!(loaded.packages[0].version, "10.2.1");
    }

    #[test]
    fn test_lockfile_remove() {
        let mut lock = Lockfile::new("abc123");
        lock.upsert(LockedPackage {
            name: "fmt".to_string(),
            version: "10.2.1".to_string(),
            source: "ion+https://registry.ion-cpp.dev".to_string(),
            checksum: "sha256:deadbeef".to_string(),
            cmake_targets: vec![],
            dependencies: vec![],
            dev_only: false,
            features: vec![],
        });
        lock.upsert(LockedPackage {
            name: "spdlog".to_string(),
            version: "1.13.0".to_string(),
            source: "ion+https://registry.ion-cpp.dev".to_string(),
            checksum: "sha256:cafebabe".to_string(),
            cmake_targets: vec![],
            dependencies: vec!["fmt 10.2.1".to_string()],
            dev_only: false,
            features: vec![],
        });

        lock.remove("fmt");
        assert_eq!(lock.packages.len(), 1);
        assert!(lock.packages[0].dependencies.is_empty());
    }

    #[test]
    fn test_manifest_hash() {
        let h1 = hash_manifest("name = \"test\"");
        let h2 = hash_manifest("name = \"test\"");
        let h3 = hash_manifest("name = \"other\"");
        assert_eq!(h1, h2);
        assert_ne!(h1, h3);
    }
}
